version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 20
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'angular-eslint'
      nx:
        patterns:
          - '@nx/*'
          - 'nx'
      aws-cdk:
        patterns:
          - 'aws-cdk'
          - 'aws-cdk-lib'
          - 'constructs'
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      typescript-eslint:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'eslint'
          - 'eslint-config-prettier'
      ngx-translate:
        patterns:
          - '@ngx-translate/*'
